"""Add 26 fields to ExtractedData

Revision ID: 61a3fe6f3c76
Revises: 87130f9275ec
Create Date: 2026-06-04 16:41:28.583324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a3fe6f3c76'
down_revision: Union[str, Sequence[str], None] = '87130f9275ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
