"""Initial migration

Revision ID: 6f08011397c4
Revises: 
Create Date: 2026-06-04 16:07:17.718533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f08011397c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_file_name'), 'documents', ['file_name'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('audit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(), nullable=True),
    sa.Column('original_value', sa.String(), nullable=True),
    sa.Column('updated_value', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_history_id'), 'audit_history', ['id'], unique=False)
    op.create_table('extracted_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('document_date', sa.String(), nullable=True),
    sa.Column('processing_date', sa.String(), nullable=True),
    sa.Column('received_date', sa.String(), nullable=True),
    sa.Column('claim_number', sa.String(), nullable=True),
    sa.Column('claimant_name', sa.String(), nullable=True),
    sa.Column('claimant_number', sa.String(), nullable=True),
    sa.Column('policy_number', sa.String(), nullable=True),
    sa.Column('date_of_loss', sa.String(), nullable=True),
    sa.Column('firm_name', sa.String(), nullable=True),
    sa.Column('firm_address', sa.String(), nullable=True),
    sa.Column('firm_vendor_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_vendor_id', sa.String(), nullable=True),
    sa.Column('amount_paid', sa.String(), nullable=True),
    sa.Column('amount_billed', sa.String(), nullable=True),
    sa.Column('eighty_percent_amount_billed', sa.String(), nullable=True),
    sa.Column('amount_owed', sa.String(), nullable=True),
    sa.Column('date_of_service_from', sa.String(), nullable=True),
    sa.Column('date_of_service_to', sa.String(), nullable=True),
    sa.Column('total_postage_cost', sa.String(), nullable=True),
    sa.Column('certification_number', sa.String(), nullable=True),
    sa.Column('documents_in_envelope', sa.String(), nullable=True),
    sa.Column('postage_cost_per_document', sa.String(), nullable=True),
    sa.Column('envelope_type', sa.String(), nullable=True),
    sa.Column('certified_mail', sa.String(), nullable=True),
    sa.Column('assignment_of_benefit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_extracted_data_claim_number'), 'extracted_data', ['claim_number'], unique=False)
    op.create_index(op.f('ix_extracted_data_claimant_name'), 'extracted_data', ['claimant_name'], unique=False)
    op.create_index(op.f('ix_extracted_data_firm_name'), 'extracted_data', ['firm_name'], unique=False)
    op.create_index(op.f('ix_extracted_data_id'), 'extracted_data', ['id'], unique=False)
    op.create_table('processing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_logs_id'), 'processing_logs', ['id'], unique=False)
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('previous_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_status_history_id'), 'status_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_status_history_id'), table_name='status_history')
    op.drop_table('status_history')
    op.drop_index(op.f('ix_processing_logs_id'), table_name='processing_logs')
    op.drop_table('processing_logs')
    op.drop_index(op.f('ix_extracted_data_id'), table_name='extracted_data')
    op.drop_index(op.f('ix_extracted_data_firm_name'), table_name='extracted_data')
    op.drop_index(op.f('ix_extracted_data_claimant_name'), table_name='extracted_data')
    op.drop_index(op.f('ix_extracted_data_claim_number'), table_name='extracted_data')
    op.drop_table('extracted_data')
    op.drop_index(op.f('ix_audit_history_id'), table_name='audit_history')
    op.drop_table('audit_history')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_file_name'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
